eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 1
  instance:
    lease-renewal-interval-in-seconds: 5
management:
  health:
    redis:
      enabled: false
server:
  port: 8111
  tomcat:
    uri-encoding: utf-8
spring:
  application:
    name: gateway
  boot:
    admin:
      url: http://localhost:8090
  cloud:
    gateway:
      routes:

      - id: SCSRV_TEST
        uri: lb://SCSRV
        predicates:
        - Path=/scsrv_Test/**
        filters:
        - StripPrefix=1
        - CheckToken=ACCESS_TOKEN
        - name: Retry
          args:
            retries: 5
            series:
            statuses:
              - INTERNAL_SERVER_ERROR
            methods:
              - GET
            exceptions:
              - java.io.IOException
              - java.util.concurrent.TimeoutException
              - java.lang.NullPointerException

      - id: TOKEN_SRV
        uri: lb://SCSRV
        predicates:
        - Path=/token_Fresh/**
        filters:
        - StripPrefix=1
        - RefreshAccessToken=user_id

      - id: SCSRV_USER
        uri: lb://SCSRV
        predicates:
        - Path=/scsrv_User/**
        filters:
        - StripPrefix=1
        - CheckToken=ACCESS_TOKEN

      - id: SCSRV_GRADE
        uri: lb://SCSRV
        predicates:
        - Path=/scsrv_Grade/**
        filters:
        - StripPrefix=1
        - CheckToken=ACCESS_TOKEN

      - id: SCSRV_LOGIN
        uri: lb://SCSRV
        predicates:
        - Path=/scsrv_Login/**
        filters:
        - StripPrefix=1
        - BuildToken=user_id

      - id: SCSRV_EXIT
        uri: lb://SCSRV
        predicates:
        - Path=/scsrv_Exit/**
        filters:
        - StripPrefix=1
        - ClearToken=user_id

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    driverClassName: com.mysql.jdbc.Driver
    filters: stat,wall
    initialSize: 5
    maxActive: 50
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 1
    password: 111111
    poolPingConnectionsNotUsedFor: 60000
    poolPreparedStatements: false
    removeAbandoned: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=CTT
    username: root
    validationQuery: SELECT 1 FROM DUAL
  redis:
    cache:
      clusterNodes: 127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005
      maxIdle: 20
      maxRedirections: 3
      maxTotal: 20
      maxWait: 1000
      minEvictableIdleTimeMillis: 1800000
      minIdle: 8
      numTestsPerEvictionRun: 3
      password: ''
      serverPort: 7000,7001,7002,7003,7004,7005
      softMinEvictableIdleTimeMillis: 1800000
      testOnBorrow: true
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      timeout: 2000

lettuce:
  redis:
    autoReconnect: true
    clusterNodes: redis://127.0.0.1:7000,redis://127.0.0.1:7001,redis://127.0.0.1:7002,redis://127.0.0.1:7003,redis://127.0.0.1:7004,redis://127.0.0.1:7005
    maxRedirects: 3

AccessToken:
  StoreTime:
    Unit: HOUR
    Value: 1
  LifePeriod:
    Unit: MINUTE
    Value: 30
RefreshToken:
  StoreTime:
    Unit: HOUR
    Value: 1
  LifePeriod:
    Unit: MINUTE
    Value: 35

LOG_HOME: /Users/yuan/logs/gateway